version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=applifting
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    image: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/applifting
    restart: unless-stopped
volumes:
  db: